# Generated by Django 5.0.1 on 2025-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
