# Generated by Django 5.0.1 on 2025-06-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_task_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_important',
        ),
    ]
